[package]
name = "tgame"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tgame-cekirdek = { path = "../tgame-cekirdek" }
tgame-mod = { path = "../tgame-mod" }
tgame-pencere = { path = "../tgame-pencere" }
tgame-sahne = { path = "../tgame-sahne" }

[lints]
workspace = true
