[package]
name = "tgame-pencere"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
pollster = "0.4.0"
tgame-cekirdek = { path = "../tgame-cekirdek" }
tgame-girdi = { path = "../tgame-girdi" }
tgame-grafik = { path = "../tgame-grafik" }
tgame-zaman = { path = "../tgame-zaman" }
winit = "0.30.13"

[lints]
workspace = true
