[package]
name = "tgame-grafik"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tgame-cekirdek = { path = "../tgame-cekirdek" }
tgame-matematik = { path = "../tgame-matematik" }
tgame-model = { path = "../tgame-model" }
tgame-varlik = { path = "../tgame-varlik" }
wgpu = "30.0.0"
winit = "0.30.13"

[lints]
workspace = true
